# Generated by Django 4.1.4 on 2022-12-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
