# Generated by Django 4.1.4 on 2022-12-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
