# Generated by Django 4.1.4 on 2023-01-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lesson_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
